[tool.poetry]
name = "biogeotrack"
version = "0.1.0"
description = "A small program to do track analysis."
authors = ["Carlos Fernando Castillo <cfcastillo@tutanota.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
vincenty = "^0.1.4"
numpy = "^1.24.2"
pandas = "^1.5.3"
pyshp = "^2.3.1"
matplotlib = "^3.7.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
